[package]
name = "auth_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["postgres","chrono"] }
dotenvy = "0.15"
chrono = {version = "0.4", features = ["serde"]}
actix-web = "4"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
