name: CI/CD for Shuttle and Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Shuttle
      run: cargo install cargo-shuttle

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Branch
      id: branch-name
      run: echo "BRANCH=$(echo $GITHUB_REF | sed 's|refs/heads/||')" >> $GITHUB_ENV

    - name: Deploy to Shuttle (Main Branch)
      if: env.BRANCH == 'main'
      env:
        SHUTTLE_API_KEY: ${{ secrets.SHUTTLE_API_KEY }}
      run: cargo shuttle deploy

    - name: Build and Push Docker Image (Dev Branch)
      if: env.BRANCH == 'dev'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true  # Push to Docker registry or leave as false if not needed
        tags: your-registry/your-image:${{ github.sha }}